name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Determine version
        id: version
        run: |
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Test
        run:  go test ./...

      - name: Build
        run: go build -o bin/liftoff ./cmd/liftoff